[project]
name = "backend"
version = "0.1.0"
description = "Backend das atividades da disciplina C216 L1"
authors = [
    {name = "bissacot",email = "gabrielfraguas@gmail.com"}
]
requires-python = ">=3.10"
dependencies = [
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn (>=0.52.4,<0.53.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)"
]
