name: Testes

on:
  push:
    branches:
      - aulas
      - pratica-3
  pull_request:
    branches:
      - aulas

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar dependencias
        working-directory: backend
        run: poetry install

      - name: Executar testes
        working-directory: backend
        run: poetry run pytest tests -v